[package]
name = "smart-rs"
version = "0.5.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]

[dependencies]
libc = "0.2"
serde = "0.9"
serde_derive = "0.9"
nom = "^2.2"
regex = "0.2"
byteorder = "1"

[target.'cfg(target_os = "freebsd")'.dependencies]
cam = { path = "cam" }

[lib]
name = "smart"
