[package]
name = "sample-scsi"
version = "0.5.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]

[dependencies]
clap = ">=0.6.6"
separator = "0.3.1"
number_prefix = "0.2.7"
smart-rs = { path = ".." }
